improve

diff --git a/autogpts/autogpt/Dockerfile b/autogpts/autogpt/Dockerfile
--- a/autogpts/autogpt/Dockerfile
+++ b/autogpts/autogpt/Dockerfile
@@ -4,14 +4,9 @@ ARG BUILD_TYPE=dev
 # Use an official Python base image from the Docker Hub
 FROM python:3.10-slim AS autogpt-base
 
-# Install browsers
+# Install browsers and necessary utilities
 RUN apt-get update && apt-get install -y \
-    chromium-driver ca-certificates gcc \
-    && apt-get clean && rm -rf /var/lib/apt/lists/*
-
-# Install utilities
-RUN apt-get update && apt-get install -y \
-    curl jq wget git \
+    chromium-driver ca-certificates gcc curl jq wget git \
     && apt-get clean && rm -rf /var/lib/apt/lists/*
 
 # Set environment variables
@@ -31,26 +26,28 @@ RUN poetry config installer.max-workers 10
 WORKDIR /app
 COPY pyproject.toml poetry.lock ./
 
+# Install dependencies for dev and release
+RUN case "${BUILD_TYPE}" in
+    dev)
+        poetry install --no-cache --no-root
+        ;;
+    release)
+        poetry install --no-cache --no-root --without dev
+        ;;
+    *)
+        echo "Invalid build type: ${BUILD_TYPE}"
+        exit 1
+        ;;
+esac
+RUN rm -rf $(poetry env info --path)/src
+
+# Copy files based on the build type
+COPY --from=build-context ${BUILD_TYPE} ./
+
 # Set the entrypoint
 ENTRYPOINT ["poetry", "run", "autogpt"]
 CMD []
 
-# dev build -> include everything
-FROM autogpt-base as autogpt-dev
-RUN poetry install --no-cache --no-root \
-    && rm -rf $(poetry env info --path)/src
+# Create a separate stage for building the final image
+FROM autogpt-base AS build-context
 ONBUILD COPY . ./
-
-# release build -> include bare minimum
-FROM autogpt-base as autogpt-release
-RUN poetry install --no-cache --no-root --without dev \
-    && rm -rf $(poetry env info --path)/src
-ONBUILD COPY autogpt/ ./autogpt
-ONBUILD COPY scripts/ ./scripts
-ONBUILD COPY plugins/ ./plugins
-ONBUILD COPY prompt_settings.yaml ./prompt_settings.yaml
-ONBUILD COPY README.md ./README.md
-ONBUILD RUN mkdir ./data
-
-FROM autogpt-${BUILD_TYPE} AS autogpt
-RUN poetry install --only-root
